version: "3.1"
services:
  jupyter:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/home/jovyan/
    ports:
      - 8888:8888
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports: 
        - "8081:8081" 
    links: 
        - db:postgres
    environment:
        - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
    depends_on:
        - db
  minio:
    image: minio/minio
    container_name: "minio"
    ports:
        - 9000:9000
    environment:
        - MINIO_ACCESS_KEY=12345678
        - MINIO_SECRET_KEY=password
    command: server /data
  superset:
    image: tylerfowler/superset
    container_name: "superset"
    ports:
        - 8088:8088
volumes:
  pgdata:
